
---

- name: add keybindings
  blockinfile:
    block: "{{ lookup('file', 'key_bindings.xml') }}"
    marker: "<!-- {mark} My keybindings -->"
    dest: ~/.config/openbox/lxde-rc.xml
    backup: yes
    insertafter: "<keyboard>"
