
---

- name: add lines
  lineinfile:
    path: ~/testbashrc
    line: PS1='\[\033[01;35m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

- name: add lines
  lineinfile:
    path: ~/testbashrc
    line: shopt -s histverify

- name: add line
  lineinfile:
    path: ~/testbashrc
    line: set -o vi
