
---

- name: add lines
  lineinfile:
    path: ~/.bashrc
    line: "{{ item }}"
  loop:
     - PS1='\[\033[01;35m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
     - shopt -s histverify
     - set -o vi  
 
